### ISSUE TITLE
Looks like being blocked by captcha

### ISSUE THREAD

**Issue by malikmajai** [horse-3903/google-reverse-image-search#1]
```
Connected...
Traceback (most recent call last):
  File "d:\Bots\Google Reverse Search\test.py", line 3, in <module>
    print(google_reverse_search.search_with_file(file_path="avatar.png",num=5))
  File "C:\Users\Rizwan computers\AppData\Local\Programs\Python\Python310\lib\site-packages\google_reverse_image_search\google_reverse_search.py", line 124, in search_with_file
    page.get_by_role("button", name="Search by image").click()
  File "C:\Users\Rizwan computers\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\sync_api\_generated.py", line 13519, in click
    self._sync(
  File "C:\Users\Rizwan computers\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_sync_base.py", line 104, in _sync
    return task.result()
  File "C:\Users\Rizwan computers\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_locator.py", line 149, in click
    return await self._frame.click(self._selector, strict=True, **params)
  File "C:\Users\Rizwan computers\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_frame.py", line 484, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "C:\Users\Rizwan computers\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\Rizwan computers\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 396, in wrap_api_call
    return await cb()
  File "C:\Users\Rizwan computers\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "role=button[name="Search by image"i]"
============================================================
```

**Comment by horse-3903** [comment]
Sorry, I haven't been updating this code. Google recently changed their Google Lens image search format, and with it changed their class names and whatnot. I am still working on adapting the code to this change, and will put out a newer version in the future
